yarnPath: .yarn/releases/yarn-4.3.1.cjs
enableGlobalCache: false
packageExtensions:
  '@fastify/cookie@*':
    dependencies:
      'fastify': '*'
  '@fastify/jwt@*':
    dependencies:
      'fastify': '*'
